const mongoose = require("mongoose");
const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");

const path = require("path");
const instance = process.argv.includes("--instance") ? process.argv[process.argv.indexOf("--instance") + 1] : "";
if (instance) {
  dotenv.config({ path: path.join(__dirname, `.env.instance${instance}`) });
} else {
  dotenv.config({ path: path.join(__dirname, ".env") });
}

const isResetMode = process.argv.includes("--reset") || process.argv.includes("-r");

// Sample Restaurant & Menu Data
const restaurantsData = [
  {
    name: "Domino's Pizza 🍕",
    description: "World-famous hand-tossed pizzas, stuffed garlic breadsticks, and warm choco lava cakes.",
    cuisine: ["Pizza", "Italian", "Fast Food"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 142,
    deliveryTime: "20-30 min",
    estimatedDeliveryTime: "20-30 min",
    deliveryFee: 1.99,
    deliveryFeeETH: 0.001,
    address: "101 Blockchain Avenue, Tech City",
    coordinates: { lat: 28.6139, lng: 77.209 },
    isOpen: true,
    ownerName: "Domino's Store Manager",
    phone: "+1 800-366-4667",
    menu: [
      {
        name: "Pepperoni Passion Pizza",
        description: "Loaded with double pepperoni slices and extra melted mozzarella on hand-tossed dough.",
        category: "Pizzas",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80",
        price: 14.99,
        priceETH: 0.005,
        priceBITE: 15,
        preparationTime: "20 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Zero-Knowledge Veggie Supreme",
        description: "Crispy bell peppers, black olives, onions, juicy tomatoes, and fresh basil.",
        category: "Pizzas",
        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80",
        price: 12.99,
        priceETH: 0.004,
        priceBITE: 12,
        preparationTime: "18 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Cheese Burst Margherita",
        description: "Classic Margherita with liquid cheddar cheese bursting from the crust.",
        category: "Pizzas",
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80",
        price: 11.99,
        priceETH: 0.0038,
        priceBITE: 11,
        preparationTime: "15 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Stuffed Garlic Breadsticks",
        description: "Freshly baked breadsticks stuffed with cheesy mozzarella and jalapeños.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80",
        price: 5.99,
        priceETH: 0.002,
        priceBITE: 5,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Spicy Chicken Wings",
        description: "Oven-roasted chicken wings tossed in fiery hot buffalo sauce.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80",
        price: 7.99,
        priceETH: 0.0026,
        priceBITE: 7,
        preparationTime: "15 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Choco Lava Cake",
        description: "Moist chocolate cake with a molten chocolate center served warm.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
        price: 4.49,
        priceETH: 0.0015,
        priceBITE: 4,
        preparationTime: "8 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Cold Chilled Pepsi",
        description: "Ice cold 500ml refreshing Pepsi bottle.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
        price: 2.49,
        priceETH: 0.0008,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Pizza Hut 🍕",
    description: "Pan pizzas, stuffed crust delights, rich pasta dishes, and oven-baked appetizers.",
    cuisine: ["Pizza", "Italian", "Fast Food"],
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 98,
    deliveryTime: "25-35 min",
    estimatedDeliveryTime: "25-35 min",
    deliveryFee: 2.49,
    deliveryFeeETH: 0.0012,
    address: "404 Crypto Boulevard, Silicon Park",
    coordinates: { lat: 28.621, lng: 77.215 },
    isOpen: true,
    ownerName: "Pizza Hut Franchise Manager",
    phone: "+1 800-749-9292",
    menu: [
      {
        name: "Ultimate Supreme Pan Pizza",
        description: "Loaded with sausage, pepperoni, beef, bell peppers, onions, and mushrooms.",
        category: "Pizzas",
        image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80",
        price: 15.99,
        priceETH: 0.0053,
        priceBITE: 16,
        preparationTime: "22 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Veggie Lover's Stuffed Crust",
        description: "Stuffed crust loaded with mushrooms, red onions, sweet corn, and green peppers.",
        category: "Pizzas",
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80",
        price: 13.49,
        priceETH: 0.0045,
        priceBITE: 13,
        preparationTime: "20 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Crispy Chicken Tenders & Dip",
        description: "Golden fried tender chicken strips served with honey mustard dip.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
        price: 8.49,
        priceETH: 0.0028,
        priceBITE: 8,
        preparationTime: "12 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Cheesy Garlic Bread",
        description: "Toasted baguette slices brushed with garlic butter and melted mozzarella.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80",
        price: 4.99,
        priceETH: 0.0017,
        priceBITE: 4,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Creamy Alfredo Pasta",
        description: "Penne pasta cooked in rich parmesan cream sauce with sautéed mushrooms.",
        category: "Pasta",
        image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
        price: 9.99,
        priceETH: 0.0033,
        priceBITE: 9,
        preparationTime: "15 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Hershey's Chocolate Chip Cookie",
        description: "8-inch freshly baked warm Hershey's chocolate chip cookie cake.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
        price: 6.99,
        priceETH: 0.0023,
        priceBITE: 6,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Mountain Dew Ice",
        description: "Citrus-flavored carbonated soda 500ml.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=600&q=80",
        price: 2.49,
        priceETH: 0.0008,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Burger King 🍔",
    description: "Flame-broiled Whopper burgers, crispy chicken royale, and golden French fries.",
    cuisine: ["Burgers", "Fast Food", "American"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 115,
    deliveryTime: "15-25 min",
    estimatedDeliveryTime: "15-25 min",
    deliveryFee: 1.99,
    deliveryFeeETH: 0.001,
    address: "12 King's Square, Web3 Plaza",
    coordinates: { lat: 28.63, lng: 77.22 },
    isOpen: true,
    ownerName: "Burger King Outlet Head",
    phone: "+1 800-538-8888",
    menu: [
      {
        name: "Double Flame-Broiled Whopper",
        description: "Two flame-broiled beef patties topped with juicy tomatoes, lettuce, mayo, and pickles.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
        price: 9.99,
        priceETH: 0.0033,
        priceBITE: 10,
        preparationTime: "12 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Impossible Veggie Whopper",
        description: "100% plant-based flame-broiled patty topped with fresh lettuce, tomatoes, and mayo.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
        price: 8.99,
        priceETH: 0.003,
        priceBITE: 9,
        preparationTime: "12 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Crispy Chicken Royale",
        description: "White meat chicken fillet, light mayo, and shredded lettuce on a sesame seed bun.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Golden Onion Rings",
        description: "Crispy battered golden fried onion rings served with zesty sauce.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "8 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Large French Fries",
        description: "Hot, thick-cut salted golden potato fries.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",
        price: 3.49,
        priceETH: 0.0011,
        priceBITE: 3,
        preparationTime: "6 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chocolate Fudge Sundae",
        description: "Soft serve vanilla ice cream smothered in hot chocolate fudge.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "5 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Coca-Cola Zero Sugar",
        description: "Chilled 500ml Coca-Cola Zero Sugar bottle.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&q=80",
        price: 2.29,
        priceETH: 0.0007,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "McDonald's 🍟",
    description: "Iconic Big Macs, McChicken burgers, world-famous fries, and cream McFlurries.",
    cuisine: ["Burgers", "Fast Food", "American"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 210,
    deliveryTime: "15-20 min",
    estimatedDeliveryTime: "15-20 min",
    deliveryFee: 1.49,
    deliveryFeeETH: 0.0008,
    address: "88 Golden Arches Lane, Crypto City",
    coordinates: { lat: 28.61, lng: 77.205 },
    isOpen: true,
    ownerName: "McDonald's Regional Lead",
    phone: "+1 800-244-6227",
    menu: [
      {
        name: "Big Mac Meal",
        description: "Double beef patties, special sauce, lettuce, cheese, pickles on sesame seed bun + fries & drink.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80",
        price: 10.49,
        priceETH: 0.0035,
        priceBITE: 10,
        preparationTime: "10 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "McSpicy Paneer Burger",
        description: "Crispy spicy paneer patty topped with jalapeno sauce and fresh lettuce.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=600&q=80",
        price: 6.99,
        priceETH: 0.0023,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chicken McNuggets (10pcs)",
        description: "Tender chicken nuggets with choice of BBQ, Tangy Honey, or Sweet & Sour dip.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
        price: 7.99,
        priceETH: 0.0026,
        priceBITE: 8,
        preparationTime: "8 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "World Famous Fries (Large)",
        description: "Crispy salted potato fries golden fried in vegetable oil.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",
        price: 3.49,
        priceETH: 0.0011,
        priceBITE: 3,
        preparationTime: "5 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Oreo McFlurry",
        description: "Creamy vanilla soft serve mixed with crushed Oreo cookies.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
        price: 4.49,
        priceETH: 0.0015,
        priceBITE: 4,
        preparationTime: "4 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "McSpicy Chicken Burger",
        description: "Juicy chicken thigh patty coated in spicy batter with tandoori mayo.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Iced Caramel Macchiato",
        description: "McCafé espresso with cold milk and sweet caramel drizzle.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "4 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "KFC 🍗",
    description: "Finger Lickin' Good fried chicken, Zinger burgers, and crispy chicken tenders.",
    cuisine: ["Fast Food", "Chicken", "American"],
    image: "https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 165,
    deliveryTime: "20-30 min",
    estimatedDeliveryTime: "20-30 min",
    deliveryFee: 2.19,
    deliveryFeeETH: 0.0011,
    address: "55 Colonel Street, Decentralized District",
    coordinates: { lat: 28.618, lng: 77.212 },
    isOpen: true,
    ownerName: "KFC Store Operator",
    phone: "+1 800-225-5532",
    menu: [
      {
        name: "8-Piece Hot & Crispy Chicken Bucket",
        description: "8 pieces of original secret recipe secret spicy fried chicken.",
        category: "Chicken Buckets",
        image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=600&q=80",
        price: 18.99,
        priceETH: 0.0063,
        priceBITE: 19,
        preparationTime: "20 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Zinger Burger",
        description: "Signature crispy chicken fillet with spicy marinade and thousand island dressing.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80",
        price: 6.49,
        priceETH: 0.0021,
        priceBITE: 6,
        preparationTime: "12 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Veg Zinger Burger",
        description: "Crispy vegetable & potato patty seasoned with Colonel's herbs and mayo.",
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80",
        price: 5.99,
        priceETH: 0.002,
        priceBITE: 6,
        preparationTime: "12 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Popcorn Chicken Large",
        description: "Bite-sized tender crispy chicken popcorn with chili lime dip.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Crispy Fries & Dip",
        description: "Skin-on seasoned potato fries served with garlic mayo dip.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",
        price: 3.49,
        priceETH: 0.0011,
        priceBITE: 3,
        preparationTime: "6 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chocolate Lava Cake",
        description: "Rich dark chocolate cake filled with gooey hot chocolate.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "6 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chilled 7UP",
        description: "Refreshing lemon-lime carbonated soft drink 500ml.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
        price: 2.19,
        priceETH: 0.0007,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Subway 🥪",
    description: "Build-your-own fresh submarine sandwiches, toasted wraps, fresh salads, and baked cookies.",
    cuisine: ["Sandwiches", "Healthy", "Fast Food"],
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    rating: 4.5,
    reviewCount: 88,
    deliveryTime: "15-25 min",
    estimatedDeliveryTime: "15-25 min",
    deliveryFee: 1.79,
    deliveryFeeETH: 0.0009,
    address: "33 Fresh Sub Way, Eco Park",
    coordinates: { lat: 28.625, lng: 77.218 },
    isOpen: true,
    ownerName: "Subway Franchise Owner",
    phone: "+1 800-888-4848",
    menu: [
      {
        name: "Italian B.M.T. Sub (12-inch)",
        description: "Salami, pepperoni, and ham on freshly baked bread with your choice of veggies and sauce.",
        category: "Subs",
        image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80",
        price: 11.49,
        priceETH: 0.0038,
        priceBITE: 11,
        preparationTime: "10 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Veggie Delite Sub (12-inch)",
        description: "Cucumbers, green peppers, tomatoes, red onions, lettuce, and spinach on wheat bread.",
        category: "Subs",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
        price: 8.99,
        priceETH: 0.003,
        priceBITE: 9,
        preparationTime: "8 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Roasted Chicken Breast Sub (6-inch)",
        description: "Juicy roasted chicken breast patty on parmesan oregano toasted sub.",
        category: "Subs",
        image: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "8 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Paneer Tikka Wrap",
        description: "Spiced grilled paneer cubes wrapped in toasted tortilla with mint mayo.",
        category: "Wraps",
        image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
        price: 6.99,
        priceETH: 0.0023,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Fresh Garden Salad",
        description: "Bed of lettuce, spinach, olives, cucumbers, and tomatoes with olive oil dressing.",
        category: "Salads",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
        price: 7.99,
        priceETH: 0.0026,
        priceBITE: 8,
        preparationTime: "6 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chocolate Chip Cookies (3pcs)",
        description: "Oven fresh soft baked chocolate chip cookies.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
        price: 3.49,
        priceETH: 0.0011,
        priceBITE: 3,
        preparationTime: "3 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Lemon Ice Tea",
        description: "Chilled brewed iced tea flavored with natural lemon juice.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
        price: 2.49,
        priceETH: 0.0008,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Behrouz Biryani 🍲",
    description: "Royal dum biryani cooked with authentic secret spices, tender meats, and saffron-infused rice.",
    cuisine: ["Biryani", "Indian", "Mughlai"],
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 175,
    deliveryTime: "30-40 min",
    estimatedDeliveryTime: "30-40 min",
    deliveryFee: 2.99,
    deliveryFeeETH: 0.0015,
    address: "77 Royal Court, Heritage Quarter",
    coordinates: { lat: 28.635, lng: 77.225 },
    isOpen: true,
    ownerName: "Royal Kitchens Head",
    phone: "+1 800-419-3333",
    menu: [
      {
        name: "Dum Gosht Mutton Biryani",
        description: "Slow-cooked tender mutton pieces layered with fragrant basmati rice and royal spices.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
        price: 16.99,
        priceETH: 0.0056,
        priceBITE: 17,
        preparationTime: "30 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Subz-e-Mahal Veg Biryani",
        description: "Royal vegetable biryani cooked with fresh veggies, paneer, and aromatic kewra water.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
        price: 12.49,
        priceETH: 0.0041,
        priceBITE: 12,
        preparationTime: "25 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Murgh Makhani Chicken Biryani",
        description: "Succulent boneless chicken tikka cooked in rich butter gravy and layered in dum biryani.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
        price: 14.99,
        priceETH: 0.005,
        priceBITE: 15,
        preparationTime: "25 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Paneer Subz Dum Biryani",
        description: "Marinated cottage cheese cubes dum cooked with saffron long grain basmati rice.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80",
        price: 13.49,
        priceETH: 0.0045,
        priceBITE: 13,
        preparationTime: "22 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Mirchi Ka Salan & Cucumber Raita",
        description: "Traditional spicy hyderabadi green chili curry accompanied with cooled yogurt raita.",
        category: "Sides",
        image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Royal Gulab Jamun (2pcs)",
        description: "Warm soft milk dumplings soaked in cardamom and rose water sugar syrup.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
        price: 4.99,
        priceETH: 0.0016,
        priceBITE: 5,
        preparationTime: "5 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Masala Mint Sharbath",
        description: "Refreshing spiced Indian cooler made with fresh mint, lemon, and cumin.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
        price: 2.99,
        priceETH: 0.001,
        priceBITE: 3,
        preparationTime: "3 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Biryani By Kilo 🍲",
    description: "Authentic handi-cooked biryani delivered fresh in traditional sealed earthen pots.",
    cuisine: ["Biryani", "Indian", "Kebabs"],
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 130,
    deliveryTime: "35-45 min",
    estimatedDeliveryTime: "35-45 min",
    deliveryFee: 3.49,
    deliveryFeeETH: 0.0018,
    address: "108 Claypot Road, Culinary District",
    coordinates: { lat: 28.64, lng: 77.23 },
    isOpen: true,
    ownerName: "Master Chef Handi Owner",
    phone: "+1 800-720-9999",
    menu: [
      {
        name: "Hyderabadi Chicken Dum Biryani (1/2kg)",
        description: "Freshly prepared chicken biryani cooked individually in earthen clay handi.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
        price: 15.49,
        priceETH: 0.0051,
        priceBITE: 15,
        preparationTime: "35 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Lucknowi Veg Dum Biryani (1/2kg)",
        description: "Mild, fragrant Nawabi vegetable biryani layered with aromatic ghee and dry fruits.",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
        price: 11.99,
        priceETH: 0.004,
        priceBITE: 12,
        preparationTime: "30 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Galouti Kebab (4pcs)",
        description: "Melt-in-mouth minced lamb kebabs marinated in 16 Awadhi spices.",
        category: "Kebabs",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80",
        price: 9.99,
        priceETH: 0.0033,
        priceBITE: 10,
        preparationTime: "20 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Paneer Tikka Kebab (4pcs)",
        description: "Tandoor-charred cottage cheese cubes marinated in yogurt and yellow chili spices.",
        category: "Kebabs",
        image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80",
        price: 8.49,
        priceETH: 0.0028,
        priceBITE: 8,
        preparationTime: "18 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Rumali Roti (2pcs)",
        description: "Paper thin delicate Indian bread cooked on inverted wok.",
        category: "Breads",
        image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80",
        price: 2.49,
        priceETH: 0.0008,
        priceBITE: 2,
        preparationTime: "8 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Phirni Dessert Bowl",
        description: "Traditional slow-cooked ground rice pudding flavored with saffron and almonds.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=600&q=80",
        price: 4.49,
        priceETH: 0.0015,
        priceBITE: 4,
        preparationTime: "5 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Royal Thandai",
        description: "Chilled milk beverage blended with almonds, pistachios, cardamom, and rose petals.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=600&q=80",
        price: 3.49,
        priceETH: 0.0011,
        priceBITE: 3,
        preparationTime: "4 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Faasos 🌯",
    description: "Flavorful rice bowls, cheesy wraps, and loaded rolls packed with fresh meats and vegetables.",
    cuisine: ["Wraps", "Rolls", "Indian", "Fast Food"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 104,
    deliveryTime: "20-30 min",
    estimatedDeliveryTime: "20-30 min",
    deliveryFee: 1.99,
    deliveryFeeETH: 0.001,
    address: "99 Rebel Kitchen Street, Metro Hub",
    coordinates: { lat: 28.628, lng: 77.211 },
    isOpen: true,
    ownerName: "Faasos Kitchen Lead",
    phone: "+1 800-555-7227",
    menu: [
      {
        name: "Jumbo Chicken Tikka Wrap",
        description: "Smoky tandoori chicken tikka, onions, and mint mayo wrapped in soft laccha paratha.",
        category: "Wraps",
        image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
        price: 7.99,
        priceETH: 0.0026,
        priceBITE: 8,
        preparationTime: "12 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Cheese Melt Paneer Wrap",
        description: "Soft paneer cubes tossed in makhani gravy with melted mozzarella cheese spread.",
        category: "Wraps",
        image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80",
        price: 6.99,
        priceETH: 0.0023,
        priceBITE: 7,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Signature Butter Chicken Rice Bowl",
        description: "Boneless butter chicken served over fragrant jeera rice with pickled onions.",
        category: "Rice Bowls",
        image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80",
        price: 9.49,
        priceETH: 0.0031,
        priceBITE: 9,
        preparationTime: "15 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Rajma Masala Rice Bowl",
        description: "Home-style kidney bean gravy served over steamed basmati rice.",
        category: "Rice Bowls",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "12 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Cheesy Corn & Jalapeno Roll",
        description: "Sweet corn kernels and spicy jalapeños tossed in cheese sauce inside crispy paratha.",
        category: "Wraps",
        image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=600&q=80",
        price: 5.99,
        priceETH: 0.002,
        priceBITE: 6,
        preparationTime: "10 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chocolate Mousse",
        description: "Light and airy whipped Belgian chocolate mousse cup.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "3 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Sweet Mango Lassi",
        description: "Thick chilled yogurt beverage blended with sweet Alphonso mango pulp.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=600&q=80",
        price: 2.99,
        priceETH: 0.001,
        priceBITE: 3,
        preparationTime: "3 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
  {
    name: "Wow! Momo 🥟",
    description: "Hot steamed, fried, and pan-tossed momos served with fiery Schezwan chutney.",
    cuisine: ["Momos", "Asian", "Fast Food"],
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 158,
    deliveryTime: "20-25 min",
    estimatedDeliveryTime: "20-25 min",
    deliveryFee: 1.89,
    deliveryFeeETH: 0.0009,
    address: "50 Himalayan Peak Road, Food Street",
    coordinates: { lat: 28.622, lng: 77.208 },
    isOpen: true,
    ownerName: "Wow! Momo Regional Partner",
    phone: "+1 800-969-6666",
    menu: [
      {
        name: "Steamed Chicken Darjeeling Momos (6pcs)",
        description: "Traditional thin-wrapper momos stuffed with juicy minced chicken and coriander.",
        category: "Momos",
        image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
        price: 6.49,
        priceETH: 0.0021,
        priceBITE: 6,
        preparationTime: "12 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Steamed Corn & Cheese Momos (6pcs)",
        description: "Steamed dumplings stuffed with sweet corn kernels and melted mozzarella cheese.",
        category: "Momos",
        image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=600&q=80",
        price: 5.99,
        priceETH: 0.002,
        priceBITE: 6,
        preparationTime: "12 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Pan-Fried Chicken Schezwan Momos (6pcs)",
        description: "Crispy pan-fried chicken dumplings tossed in spicy garlic Schezwan sauce.",
        category: "Momos",
        image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=600&q=80",
        price: 7.49,
        priceETH: 0.0025,
        priceBITE: 7,
        preparationTime: "15 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Kurkure Veg Crispy Momos (6pcs)",
        description: "Crunchy cornflake-crusted fried vegetable momos served with spicy dip.",
        category: "Momos",
        image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=600&q=80",
        price: 6.99,
        priceETH: 0.0023,
        priceBITE: 7,
        preparationTime: "14 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Thukpa Noodle Soup Bowl",
        description: "Hot Tibetan chicken noodle soup with fresh spring vegetables and herbs.",
        category: "Soups",
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80",
        price: 8.49,
        priceETH: 0.0028,
        priceBITE: 8,
        preparationTime: "15 min",
        isVeg: false,
        isAvailable: true,
      },
      {
        name: "Chocolate Momo (2pcs)",
        description: "Steamed sweet momos filled with molten hot chocolate.",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
        price: 3.99,
        priceETH: 0.0013,
        priceBITE: 4,
        preparationTime: "8 min",
        isVeg: true,
        isAvailable: true,
      },
      {
        name: "Chilled Peach Ice Tea",
        description: "Refreshing cold brewed iced tea with real peach flavor 500ml.",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
        price: 2.49,
        priceETH: 0.0008,
        priceBITE: 2,
        preparationTime: "2 min",
        isVeg: true,
        isAvailable: true,
      },
    ],
  },
];

async function seedDatabase() {
  try {
    const connStr = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/blockbite";
    await mongoose.connect(connStr, { serverSelectionTimeoutMS: 5000 });
    console.log("✓ Connected to MongoDB");

    const existingCount = await Restaurant.countDocuments();

    if (!isResetMode && existingCount > 0) {
      console.log("✓ Restaurants already exist. Skipping seeding.");
      await mongoose.disconnect();
      process.exit(0);
    }

    if (isResetMode) {
      await Restaurant.deleteMany({});
      await MenuItem.deleteMany({});
      console.log("✓ Cleared existing restaurants and menu items");
    } else {
      console.log("✓ Restaurants collection empty");
    }

    // Ensure demo users exist
    const salt = await bcrypt.genSalt(10);
    const defaultPassword = await bcrypt.hash("password123", salt);

    let defaultOwner = await User.findOne({ walletAddress: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8" });
    if (!defaultOwner) {
      defaultOwner = await User.create({
        name: "Chef Mario Rossi",
        email: "mario@pizzabite.eth",
        password: defaultPassword,
        role: "restaurant",
        walletAddress: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
        referralCode: "MARIO99",
      });
    }

    let customerUser = await User.findOne({ walletAddress: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" });
    if (!customerUser) {
      await User.create({
        name: "Alice Etherton (Customer)",
        email: "customer@blockbite.eth",
        password: defaultPassword,
        role: "customer",
        walletAddress: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        referralCode: "ALICE100",
      });
    }

    let driverUser = await User.findOne({ walletAddress: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc" });
    if (!driverUser) {
      await User.create({
        name: "Alex Vance (Rider)",
        email: "driver@blockbite.eth",
        password: defaultPassword,
        role: "driver",
        walletAddress: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc",
        referralCode: "SPEEDY07",
      });
    }

    // Insert 10 restaurants and their menu items
    let insertedRestaurantsCount = 0;

    for (const restData of restaurantsData) {
      const { menu, ...restFields } = restData;

      const restaurant = await Restaurant.create({
        ...restFields,
        owner: defaultOwner._id,
        walletAddress: defaultOwner.walletAddress,
      });

      insertedRestaurantsCount++;

      const menuItemsToInsert = menu.map((item) => ({
        ...item,
        restaurant: restaurant._id,
        title: item.name,
        diet: item.isVeg ? "Veg" : "Non-Veg",
      }));

      await MenuItem.insertMany(menuItemsToInsert);
    }

    console.log(`✓ Inserted ${insertedRestaurantsCount} restaurants`);
    console.log("✓ Database seeding completed");

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    await mongoose.disconnect();
    process.exit(1);
  }
}

seedDatabase();
